### ISSUE TITLE
Android Messages new URL

### ISSUE THREAD

**Issue by jpshelley** [dweinber/franz-recipe-android-messages#5]
It appears Messages for Web has a new URL

<img width="784" alt="Screen Shot 2019-04-05 at 9 15 13 AM" src="https://user-images.githubusercontent.com/2798846/55634107-60549900-5783-11e9-9675-db1e9b01088a.png">

Should be a simple fix to use the new url in the plugin if someone knows how to update that.

**Comment by vishnureddy17** [comment]
Looks like it was fixed in 9aa4996.

**Comment by jpshelley** [comment]
Indeed! I think I just had to uninstall the service and install it again. Fixed.
