### ISSUE TITLE
The requested URL was not found on this server.

### ISSUE THREAD

**Issue by gitrummy** [dweinber/franz-recipe-android-messages#7]
When adding the service for the first time, it works as expected, but opening Franz and loading the service after that results in an error 400.

![Franz Android Messages Error 400](https://user-images.githubusercontent.com/11849147/64657117-0ff60b80-d486-11e9-8473-703682a74d1b.png)

**Comment by dweinber** [comment]
Hi @rummystrong,

Thanks for reporting, but it seems as just the page had an error. Is that why you closed it? Is it working again?
